### This script includes the following points:

#### 1. Import the data
#### 2. Memory optimization
#### 3. combine two data frames
#### 9. Exporting Figures

#### 1. Import the data

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [2]:
path = r"C:\Users\Poory\OneDrive\Desktop\project\Instacart Basket Analysis"

In [3]:
df = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'final.pkl'))
df_dep = pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'departments_wrangled.csv'), index_col = False)

In [4]:
pd.options.display.max_rows = None
pd.options.display.max_columns = None

In [5]:
df

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,last_order_days,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_spent,spending_flag,order_freq_med,frequency_flag,last_name,gender,state,age,date_joined,n_dependants,fam_status,income
0,2539329,1,1,2,8,NaN,True,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
1,2398795,1,2,3,7,15.0,False,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Two Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
2,473747,1,3,3,12,21.0,False,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Two Least busy days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
3,2254736,1,4,4,7,29.0,False,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Two Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
4,431534,1,5,4,15,28.0,False,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Two Least busy days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32404854,156685,106143,26,4,23,5.0,False,19675,1,1,Organic Raspberry Black Tea,94,7,10.7,Mid-range product,Least busy,Two Least busy days,Fewest Orders,26,Regular customer,10.700000,High spender,7.0,Frequent customer,Yates,Male,Hawaii,25,5/26/2017,0,single,53755
32404855,484769,66343,1,6,11,NaN,True,47210,1,0,Fresh Farmed Tilapia Fillet,15,12,8.1,Mid-range product,Regularly busy,Regularly busy,Most Orders,4,New customer,8.100000,Low spender,30.0,Non-frequent customer,Arroyo,Female,Tennessee,22,9/12/2017,3,married,46151
32404856,1561557,66343,2,1,11,30.0,False,47210,1,1,Fresh Farmed Tilapia Fillet,15,12,8.1,Mid-range product,Regularly busy,Two busiest days,Most Orders,4,New customer,8.100000,Low spender,30.0,Non-frequent customer,Arroyo,Female,Tennessee,22,9/12/2017,3,married,46151
32404857,276317,66343,3,6,15,19.0,False,47210,1,1,Fresh Farmed Tilapia Fillet,15,12,8.1,Mid-range product,Regularly busy,Regularly busy,Most Orders,4,New customer,8.100000,Low spender,30.0,Non-frequent customer,Arroyo,Female,Tennessee,22,9/12/2017,3,married,46151
32404858,2922475,66343,4,1,12,30.0,False,47210,1,1,Fresh Farmed Tilapia Fillet,15,12,8.1,Mid-range product,Regularly busy,Two busiest days,Most Orders,4,New customer,8.100000,Low spender,30.0,Non-frequent customer,Arroyo,Female,Tennessee,22,9/12/2017,3,married,46151

In [6]:
# Drop last_name column due to PII
df.drop(columns = 'last_name', inplace = True)

In [7]:
df_dep

    Unnamed: 0       department
0            1           frozen
1            2            other
2            3           bakery
3            4          produce
4            5          alcohol
5            6    international
6            7        beverages
7            8             pets
8            9  dry goods pasta
9           10             bulk
10          11    personal care
11          12     meat seafood
12          13           pantry
13          14        breakfast
14          15     canned goods
15          16       dairy eggs
16          17        household
17          18           babies
18          19           snacks
19          20             deli
20          21          missing

In [8]:
df_dep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  21 non-null     int64
 1   department  21 non-null     object
dtypes: int64(1), object(1)
memory usage: 468.0+ bytes

In [9]:
# Change Unnamed column name to department_id
df_dep.rename(columns = {'Unnamed: 0':'department_id'}, inplace = True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32404859 entries, 0 to 32404858
Data columns (total 31 columns):
 #   Column                 Dtype
---  ------                 -----
 0   order_id               int32
 1   user_id                int32
 2   order_number           int8
 3   orders_day_of_week     int8
 4   order_hour_of_day      int8
 5   last_order_days        float16
 6   first_order            bool
 7   product_id             int32
 8   add_to_cart_order      int32
 9   reordered              int8
 10  product_name           object
 11  aisle_id               int64
 12  department_id          int64
 13  prices                 float64
 14  price_range            object
 15  busiest_day            object
 16  busiest_days           object
 17  busiest_period_of_day  object
 18  max_order              int8
 19  loyalty_flag           object
 20  avg_spent              float64
 21  spending_flag          object
 22  order_freq_med         float16
 23  frequency_flag         object
 24  gender                 object
 25  state                  object
 26  age                    int64
 27  date_joined            object
 28  n_dependants           int64
 29  fam_status             object
 30  income                 int64
dtypes: bool(1), float16(2), float64(2), int32(4), int64(5), int8(5), object(12)
memory usage: 5.4+ GB

### Memory optimization

In [11]:
# Change some columne data type to optimize memory
df['aisle_id'] = df['aisle_id'].astype('int32')
df['department_id'] = df['department_id'].astype('int32')
df_dep['department_id'] = df_dep['department_id'].astype('int32')
df['prices'] = df['prices'].astype('float32')
df['avg_spent'] = df['avg_spent'].astype('float32')
df['age'] = df['age'].astype('int32')
df['n_dependants'] = df['n_dependants'].astype('int32')

### Combine two Dataframes

In [12]:
# Combine two data frames 
df = df.merge(df_dep, on = 'department_id', indicator = True)

In [13]:
df['_merge'].value_counts(dropna=False)

_merge
both          32404859
left_only            0
right_only           0
Name: count, dtype: int64

In [14]:
df.drop(columns = '_merge', inplace = True)

In [15]:
# Make a new dataframe to change days of the week column values to their name
dict = {'orders_day_of_week':[0, 1, 2, 3, 4, 5, 6], 'orders_day':['Saturday', 'Sunday', 'Monday','Tuesday', 'Wednesday', 'Thursday', 'Friday']}
df_days = pd.DataFrame(dict)
df_days

   orders_day_of_week orders_day
0                   0   Saturday
1                   1     Sunday
2                   2     Monday
3                   3    Tuesday
4                   4  Wednesday
5                   5   Thursday
6                   6     Friday

In [16]:
df_days['orders_day_of_week'].dtype

dtype('int64')

In [17]:
df_days['orders_day_of_week'] = df_days['orders_day_of_week'].astype('int8')
df_days['orders_day_of_week'].dtype

dtype('int8')

In [18]:
# Combine two data frames
df = df.merge(df_days, on = 'orders_day_of_week', indicator = True)

In [19]:
df['_merge'].value_counts(dropna=False)

_merge
both          32404859
left_only            0
right_only           0
Name: count, dtype: int64

In [20]:
df.drop(columns = '_merge', inplace = True)

In [21]:
df.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,last_order_days,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_spent,spending_flag,order_freq_med,frequency_flag,gender,state,age,date_joined,n_dependants,fam_status,income,department,orders_day
0,2539329,1,1,2,8,NaN,True,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,10,New customer,6.367796,Low spender,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,beverages,Monday
1,3367565,1,6,2,7,19.0,False,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,10,New customer,6.367796,Low spender,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,beverages,Monday
2,1870022,15,17,2,16,8.0,False,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,22,Regular customer,3.980556,Low spender,10.0,Frequent customer,Female,Indiana,69,6/3/2019,0,divorced/widowed,54313,beverages,Monday
3,1911383,15,18,2,11,7.0,False,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,22,Regular customer,3.980556,Low spender,10.0,Frequent customer,Female,Indiana,69,6/3/2019,0,divorced/widowed,54313,beverages,Monday
4,887727,15,9,2,13,7.0,False,14715,1,1,Coconut Water,98,7,4.0,Low-range product,Regularly busy,Regularly busy,Most Orders,22,Regular customer,3.980556,Low spender,10.0,Frequent customer,Female,Indiana,69,6/3/2019,0,divorced/widowed,54313,beverages,Monday
5,2600170,15,11,2,9,14.0,False,14715,1,1,Coconut Water,98,7,4.0,Low-range product,Regularly busy,Regularly busy,Most Orders,22,Regular customer,3.980556,Low spender,10.0,Frequent customer,Female,Indiana,69,6/3/2019,0,divorced/widowed,54313,beverages,Monday
6,1870022,15,17,2,16,8.0,False,14715,3,1,Coconut Water,98,7,4.0,Low-range product,Regularly busy,Regularly busy,Most Orders,22,Regular customer,3.980556,Low spender,10.0,Frequent customer,Female,Indiana,69,6/3/2019,0,divorced/widowed,54313,beverages,Monday
7,1110781,21,29,2,9,8.0,False,44632,1,1,Sparkling Water Grapefruit,115,7,4.2,Low-range product,Regularly busy,Regularly busy,Most Orders,33,Regular customer,7.012683,Low spender,7.5,Frequent customer,Male,Montana,71,6/18/2019,0,divorced/widowed,124643,beverages,Monday
8,1953572,21,17,2,15,1.0,False,48988,1,1,Unsweetened Premium Iced Tea,94,7,5.7,Mid-range product,Regularly busy,Regularly busy,Most Orders,33,Regular customer,7.012683,Low spender,7.5,Frequent customer,Male,Montana,71,6/18/2019,0,divorced/widowed,124643,beverages,Monday
9,2941505,21,23,2,13,6.0,False,48988,3,1,Unsweetened Premium Iced Tea,94,7,5.7,Mid-range product,Regularly busy,Regularly busy,Most Orders,33,Regular customer,7.012683,Low spender,7.5,Frequent customer,Male,Montana,71,6/18/2019,0,divorced/widowed,124643,beverages,Monday
10,1674891,21,18,2,11,21.0,False,14788,3,1,Unsweetened Iced Tea,94,7,8.1,Mid-range product,Regularly busy,Regularly busy,Most Orders,33,Regular customer,7.012683,Low spender,7.5,Frequent customer,Male,Montana,71,6/18/2019,0,divorced/widowed,124643,beverages,Monday
11,1953572,21,17,2,15,1.0,False,10957,3,0,Fridge Pack Cola,77,7,2.7,Low-range product,Regularly busy,Regularly busy,Most Orders,33,Regular customer,7.012683,Low spender,7.5,Frequent customer,Male,Montana,71,6/18/2019,0,divorced/widowed,124643,beverages,Monday
12,2951746,31,14,2,9,6.0,False,48142,19,0,Diet,77,7,1.9,Low-range product,Regularly busy,Regularly busy,Most Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
13,2951746,31,14,2,9,6.0,False,44375,2,1,Canned Aranciata Orange,77,7,3.9,Low-range product,Regularly busy,Regularly busy,Most Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
14,2647083,31,16,2,8,8.0,False,21953,7,1,Millennium Organic Cherry Chia Synergy Kombucha,31,7,12.2,Mid-range product,Regularly busy,Regularly busy,Average Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
15,1341128,31,7,2,13,2.0,False,12440,1,1,California Lemonade,31,7,1.3,Low-range product,Regularly busy,Regularly busy,Most Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
16,2647083,31,16,2,8,8.0,False,12440,4,1,California Lemonade,31,7,1.3,Low-range product,Regularly busy,Regularly busy,Average Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
17,2951746,31,14,2,9,6.0,False,6631,3,1,No Pulp Calcium & Vitamin D Pure Orange Juice,31,7,2.9,Low-range product,Regularly busy,Regularly busy,Most Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
18,2647083,31,16,2,8,8.0,False,2197,23,1,Sparkling Pink Lemonade,77,7,2.5,Low-range product,Regularly busy,Regularly busy,Average Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
19,2951746,31,14,2,9,6.0,False,41406,17,1,Orange Soda,77,7,10.5,Mid-range product,Regularly busy,Regularly busy,Most Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
20,2647083,31,16,2,8,8.0,False,41406,34,1,Orange Soda,77,7,10.5,Mid-range product,Regularly busy,Regularly busy,Average Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
21,2951746,31,14,2,9,6.0,False,16696,26,1,Coke Classic,77,7,7.5,Mid-range product,Regularly busy,Regularly busy,Most Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
22,2647083,31,16,2,8,8.0,False,16696,33,1,Coke Classic,77,7,7.5,Mid-range product,Regularly busy,Regularly busy,Average Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
23,2647083,31,16,2,8,8.0,False,10341,32,1,Organic Honey Green Tea Drink,94,7,6.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
24,2647083,31,16,2,8,8.0,False,45036,16,1,Organic Half Tea & Half Lemonade,94,7,14.3,Mid-range product,Regularly busy,Regularly busy,Average Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
25,2647083,31,16,2,8,8.0,False,28577,30,1,No Pulp Orange Juice,31,7,4.3,Low-range product,Regularly busy,Regularly busy,Average Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
26,2951746,31,14,2,9,6.0,False,4138,1,0,Arancita Rossa,77,7,1.3,Low-range product,Regularly busy,Regularly busy,Most Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
27,2951746,31,14,2,9,6.0,False,25518,4,0,Guava Guayasa Zero,94,7,8.8,Mid-range product,Regularly busy,Regularly busy,Most Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
28,2647083,31,16,2,8,8.0,False,25518,17,1,Guava Guayasa Zero,94,7,8.8,Mid-range product,Regularly busy,Regularly busy,Average Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
29,2951746,31,14,2,9,6.0,False,2870,5,0,"Clean Energy Drink, Lemon Lemongrass",94,7,8.4,Mid-range product,Regularly busy,Regularly busy,Most Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
30,2951746,31,14,2,9,6.0,False,38376,6,0,Clean Energy Zero Lime,94,7,12.4,Mid-range product,Regularly busy,Regularly busy,Most Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
31,2647083,31,16,2,8,8.0,False,38376,18,1,Clean Energy Zero Lime,94,7,12.4,Mid-range product,Regularly busy,Regularly busy,Average Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
32,2951746,31,14,2,9,6.0,False,34177,7,0,Traditional Clean Energy Drink,94,7,1.8,Low-range product,Regularly busy,Regularly busy,Most Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
33,2647083,31,16,2,8,8.0,False,34177,19,1,Traditional Clean Energy Drink,94,7,1.8,Low-range product,Regularly busy,Regularly busy,Average Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
34,2951746,31,14,2,9,6.0,False,21131,18,0,Lemon-Lime Fridge Pack Soda,77,7,7.3,Mid-range product,Regularly busy,Regularly busy,Most Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
35,2647083,31,16,2,8,8.0,False,11148,10,0,Sparkling Cranberry Juice,77,7,3.5,Low-range product,Regularly busy,Regularly busy,Average Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
36,2647083,31,16,2,8,8.0,False,29529,25,0,Lemon-Lime Soda,77,7,14.4,Mid-range product,Regularly busy,Regularly busy,Average Orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer,Female,Oklahoma,38,1/22/2019,1,married,52311,beverages,Monday
37,580568,52,5,2,10,8.0,False,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer,Female,Alabama,64,1/30/2018,2,married,40974,beverages,Monday
38,2428073,52,7,2,7,8.0,False,196,5,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer,Female,Alabama,64,1/30/2018,2,married,40974,beverages,Monday
39,1520353,52,10,2,10,8.0,False,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer,Female,Alabama,64,1/30/2018,2,married,40974,beverages,Monday
40,2542086,52,11,2,9,7.0,False,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer,Female,Alabama,64,1/30/2018,2,married,40974,beverages,Monday
41,1268191,52,15,2,11,8.0,False,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer,Female,Alabama,64,1/30/2018,2,married,40974,beverages,Monday
42,1122089,52,17,2,10,6.0,False,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer,Female,Alabama,64,1/30/2018,2,married,40974,beverages,Monday
43,1498922,52,18,2,10,14.0,False,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer,Female,Alabama,64,1/30/2018,2,married,40974,beverages,Monday
44,580568,52,5,2,10,8.0,False,46149,4,1,Zero Calorie Cola,77,7,13.4,Mid-range product,Regularly busy,Regularly busy,Most Orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer,Female,Alabama,64,1/30/2018,2,married,40974,beverages,Monday
45,2428073,52,7,2,7,8.0,False,46149,4,1,Zero Calorie Cola,77,7,13.4,Mid-range product,Regularly busy,Regularly busy,Average Orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer,Female,Alabama,64,1/30/2018,2,married,40974,beverages,Monday
46,1520353,52,10,2,10,8.0,False,46149,3,1,Zero Calorie Cola,77,7,13.4,Mid-range product,Regularly busy,Regularly busy,Most Orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer,Female,Alabama,64,1/30/2018,2,married,40974,beverages,Monday
47,2542086,52,11,2,9,7.0,False,46149,2,1,Zero Calorie Cola,77,7,13.4,Mid-range product,Regularly busy,Regularly busy,Most Orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer,Female,Alabama,64,1/30/2018,2,married,40974,beverages,Monday
48,1268191,52,15,2,11,8.0,False,46149,4,1,Zero Calorie Cola,77,7,13.4,Mid-range product,Regularly busy,Regularly busy,Most Orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer,Female,Alabama,64,1/30/2018,2,married,40974,beverages,Monday
49,1122089,52,17,2,10,6.0,False,46149,5,1,Zero Calorie Cola,77,7,13.4,Mid-range product,Regularly busy,Regularly busy,Most Orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer,Female,Alabama,64,1/30/2018,2,married,40974,beverages,Monday
50,1498922,52,18,2,10,14.0,False,46149,3,1,Zero Calorie Cola,77,7,13.4,Mid-range product,Regularly busy,Regularly busy,Most Orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer,Female,Alabama,64,1/30/2018,2,married,40974,beverages,Monday
51,1268191,52,15,2,11,8.0,False,13259,5,0,Organic Variety Pack,98,7,13.8,Mid-range product,Regularly busy,Regularly busy,Most Orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer,Female,Alabama,64,1/30/2018,2,married,40974,beverages,Monday
52,2037087,67,4,2,9,8.0,False,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer,Female,Iowa,66,6/5/2017,1,married,115696,beverages,Monday
53,2048527,67,8,2,11,7.0,False,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer,Female,Iowa,66,6/5/2017,1,married,115696,beverages,Monday
54,2389031,67,9,2,14,7.0,False,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer,Female,Iowa,66,6/5/2017,1,married,115696,beverages,Monday
55,1928050,67,12,2,12,8.0,False,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer,Female,Iowa,66,6/5/2017,1,married,115696,beverages,Monday
56,1812985,81,5,2,20,30.0,False,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,7,New customer,8.165384,Low spender,30.0,Non-frequent customer,Male,Ohio,49,11/4/2017,1,married,123542,beverages,Monday
57,343588,82,10,2,11,1.0,False,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,19,Regular customer,6.441221,Low spender,11.5,Regular customer,Male,Oklahoma,60,5/16/2017,3,married,45982,beverages,Monday
58,3034663,82,15,2,11,12.0,False,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,19,Regular customer,6.441221,Low spender,11.5,Regular customer,Male,Oklahoma,60,5/16/2017,3,married,45982,beverages,Monday
59,3144004,82,19,2,15,8.0,False,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,19,Regular customer,6.441221,Low spender,11.5,Regular customer,Male,Oklahoma,60,5/16/2017,3,married,45982,beverages,Monday
60,3273029,120,3,2,8,19.0,False,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,3,New customer,9.385715,Low spender,19.0,Regular customer,Female,Kentucky,54,3/2/2017,2,married,99219,beverages,Monday
61,3273029,120,3,2,8,19.0,False,46149,1,1,Zero Calorie Cola,77,7,13.4,Mid-range product,Regularly busy,Regularly busy,Average Orders,3,New customer,9.385715,Low spender,19.0,Regular customer,Female,Kentucky,54,3/2/2017,2,married,99219,beverages,Monday
62,3273029,120,3,2,8,19.0,False,31102,3,1,Sugar Free Energy Drink,64,7,8.9,Mid-range product,Regularly busy,Regularly busy,Average Orders,3,New customer,9.385715,Low spender,19.0,Regular customer,Female,Kentucky,54,3/2/2017,2,married,99219,beverages,Monday
63,1779324,185,6,2,13,30.0,False,47141,1,1,Cola,77,7,14.6,Mid-range product,Regularly busy,Regularly busy,Most Orders,6,New customer,7.715000,Low spender,25.0,Non-frequent customer,Male,Oregon,51,6/21/2018,3,married,100039,beverages,Monday
64,2377728,185,5,2,14,30.0,False,33198,1,1,Sparkling Natural Mineral Water,115,7,4.0,Low-range product,Regularly busy,Regularly busy,Most Orders,6,New customer,7.715000,Low spender,25.0,Non-frequent customer,Male,Oregon,51,6/21/2018,3,married,100039,beverages,Monday
65,1779324,185,6,2,13,30.0,False,33198,2,1,Sparkling Natural Mineral Water,115,7,4.0,Low-range product,Regularly busy,Regularly busy,Most Orders,6,New customer,7.715000,Low spender,25.0,Non-frequent customer,Male,Oregon,51,6/21/2018,3,married,100039,beverages,Monday
66,2377728,185,5,2,14,30.0,False,41276,2,0,Energy Drink,64,7,10.2,Mid-range product,Regularly busy,Regularly busy,Most Orders,6,New customer,7.715000,Low spender,25.0,Non-frequent customer,Male,Oregon,51,6/21/2018,3,married,100039,beverages,Monday
67,1779324,185,6,2,13,30.0,False,15424,3,1,Purified Water,115,7,13.3,Mid-range product,Regularly busy,Regularly busy,Most Orders,6,New customer,7.715000,Low spender,25.0,Non-frequent customer,Male,Oregon,51,6/21/2018,3,married,100039,beverages,Monday
68,1738718,195,31,2,8,4.0,False,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average Orders,58,Loyal customer,7.149730,Low spender,4.0,Frequent customer,Female,South Dakota,50,6/17/2017,2,married,70952,beverages,Monday
69,1485596,195,37,2,15,0.0,False,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,58,Loyal customer,7.149730,Low spender,4.0,Frequent customer,Female,South Dakota,50,6/17/2017,2,married,70952,beverages,Monday
70,1302290,195,14,2,8,8.0,False,46149,1,1,Zero Calorie Cola,77,7,13.4,Mid-range product,Regularly busy,Regularly busy,Average Orders,58,Loyal customer,7.149730,Low spender,4.0,Frequent customer,Female,South Dakota,50,6/17/2017,2,married,70952,beverages,Monday
71,3278937,195,15,2,8,0.0,False,46149,2,1,Zero Calorie Cola,77,7,13.4,Mid-range product,Regularly busy,Regularly busy,Average Orders,58,Loyal customer,7.149730,Low spender,4.0,Frequent customer,Female,South Dakota,50,6/17/2017,2,married,70952,beverages,Monday
72,1738718,195,31,2,8,4.0,False,46149,1,1,Zero Calorie Cola,77,7,13.4,Mid-range product,Regularly busy,Regularly busy,Average Orders,58,Loyal customer,7.149730,Low spender,4.0,Frequent customer,Female,South Dakota,50,6/17/2017,2,married,70952,beverages,Monday
73,1485596,195,37,2,15,0.0,False,46149,1,1,Zero Calorie Cola,77,7,13.4,Mid-range product,Regularly busy,Regularly busy,Most Orders,58,Loyal customer,7.149730,Low spender,4.0,Frequent customer,Female,South Dakota,50,6/17/2017,2,married,70952,beverages,Monday
74,1738718,195,31,2,8,4.0,False,15164,3,1,De Mexico Bottle,77,7,11.7,Mid-range product,Regularly busy,Regularly busy,Average Orders,58,Loyal customer,7.149730,Low spender,4.0,Frequent customer,Female,South Dakota,50,6/17/2017,2,married,70952,beverages,Monday
75,1485596,195,37,2,15,0.0,False,15164,3,1,De Mexico Bottle,77,7,11.7,Mid-range product,Regularly busy,Regularly busy,Most Orders,58,Loyal customer,7.149730,Low spender,4.0,Frequent customer,Female,South Dakota,50,6/17/2017,2,married,70952,beverages,Monday
76,2505656,222,17,2,12,1.0,False,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most Orders,70,Loyal customer,6.862397,Low spender,5.0,Frequent customer,Female,Kentucky,76,4/1/2020,2,married,53488,beverages,Monday

### Exporting Data

In [22]:
# Exporting my final Data frame
df.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'Final2.pkl'))
df_dep.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'departments_wrangled.csv'))